variables:
    REPO_NAME: gitlab.com/technonauts/akordo

stages:
    - test
    - build
    - deploy

unit-tests:
    stage: test
    image: golang:latest
    tags:
        - building
        - testing
    rules:
        - if: $CI_MERGE_REQUEST_ID                # Execute jobs in merge request context
        - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
    script:
        # setup environment
        - mkdir -p /root/akordo/
        - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
        - cd $GOPATH/src/$REPO_NAME
        # run testing
        - go fmt $(go list ./... | grep -v /vendor/)
        # Ignoring go vet since imported package forces the use of unkeyed fields in some structs
        #- go vet $(go list ./... | grep -v /vendor/)
        - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    image: golang:latest
    tags:
        - building
        - testing
    rules:
        - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
    script:
        # setup environment
        - mkdir -p /root/akordo/
        - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
        - cd $GOPATH/src/$REPO_NAME
        # start build
        - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/akordo
        - cp $CI_PROJECT_DIR/akordo /root/akordo/versions/akordo

run:
    stage: deploy
    tags:
        - deploy
        - prod
    rules:
        - if: $CI_COMMIT_TAG  # Execute jobs when a new tag is pushed
    script:
        # If akordo is running then request a graceful shutdown
        - if [ $(pgrep akordo) ]; then kill -15 $(pgrep akrodo); fi
        - cd /home/techadmin/akordo/
        # When a file is opened and locked by a process, any other process is not allowed to write into it,
        # and in particular to completely overwrite it. But anyone (with the necessary rights) can rename it.
        - mv akordo akordo.prev
        # remane version with commit tag
        - mv /home/techadmin/akordo/versions/akordo /home/techadmin/akordo/versions/akordo-$CI_COMMIT_TAG
        # copy current version to directory with base name
        - cp /home/techadmin/akordo/versions/akordo-$CI_COMMIT_TAG /home/techadmin/akordo/akordo
        - source envars
        - ./akordo &
        - if [ $(pgrep akordo) ]; then exit 0; else exit 1; fi
