variables:
    REPO_NAME: gitlab.com/technonauts/akordo

stages:
    - test
    - build
    - deploy

unit-tests:
    stage: test
    tags:
        - building
        - testing
    rules:
        - if: $CI_MERGE_REQUEST_ID                # Execute jobs in merge request context
        - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
    script:
        # setup environment
        - mkdir -p /root/akordo/
        - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
        - cd $GOPATH/src/$REPO_NAME
        # run testing
        - go fmt $(go list ./... | grep -v /vendor/)
        # Ignoring go vet since imported package forces the use of unkeyed fields in some structs
        #- go vet $(go list ./... | grep -v /vendor/)
        - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    tags:
        - building
        - testing
    rules:
        - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch
    script:
        # setup environment
        - mkdir -p /root/akordo/
        - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
        - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
        - cd $GOPATH/src/$REPO_NAME
        # start build
        - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/akordo
        - cp $CI_PROJECT_DIR/akordo /root/akordo/versions/akordo

run:
    stage: deploy
    tags:
        - deploy
        - prod
    rules:
        - if: $CI_COMMIT_TAG  # Execute jobs when a new tag is pushed
    script:
        - kill $(pgrep akordo) # If akordo is not running this stage will fail
        - cd /home/techadmin/akordo/
        - mv /home/techadmin/akordo/versions/akordo /home/techadmin/akordo/versions/akordo-$CI_COMMIT_TAG
        - cp /home/techadmin/akordo/versions/akordo-$CI_COMMIT_TAG /home/techadmin/akordo/akordo
        - source envars
        - ./akordo &
