// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	discordgo "github.com/bwmarrin/discordgo"
	mock "github.com/stretchr/testify/mock"
)

// DgSession is an autogenerated mock type for the DgSession type
type DgSession struct {
	mock.Mock
}

// GuildMemberRoleAdd provides a mock function with given fields: guildID, userID, roleID
func (_m *DgSession) GuildMemberRoleAdd(guildID string, userID string, roleID string) error {
	ret := _m.Called(guildID, userID, roleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(guildID, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GuildMemberRoleRemove provides a mock function with given fields: guildID, userID, roleID
func (_m *DgSession) GuildMemberRoleRemove(guildID string, userID string, roleID string) error {
	ret := _m.Called(guildID, userID, roleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(guildID, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GuildRoles provides a mock function with given fields: guildID
func (_m *DgSession) GuildRoles(guildID string) ([]*discordgo.Role, error) {
	ret := _m.Called(guildID)

	var r0 []*discordgo.Role
	if rf, ok := ret.Get(0).(func(string) []*discordgo.Role); ok {
		r0 = rf(guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*discordgo.Role)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guildID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
