// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	discordgo "github.com/bwmarrin/discordgo"
	mock "github.com/stretchr/testify/mock"
)

// AkSession is an autogenerated mock type for the AkSession type
type AkSession struct {
	mock.Mock
}

// Channel provides a mock function with given fields: channelID
func (_m *AkSession) Channel(channelID string) (*discordgo.Channel, error) {
	ret := _m.Called(channelID)

	var r0 *discordgo.Channel
	if rf, ok := ret.Get(0).(func(string) *discordgo.Channel); ok {
		r0 = rf(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discordgo.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
